### ISSUE TITLE
Criar Arte para o Meetup de 29/07

### ISSUE THREAD

**Issue by rischioto** [hyperledgerbrasil/meetup-br#2]
Criar Arte para o Meetup de 29/07. 

### Palestra 1:
**Titulo:** IBM Blockchain Platform 2.5
**Palestrante:** Glauco Reis
**MiniBio:** Glauco Reis é mestre em Engenharia Eletrica, com concentração em Inteligência Artificial e Teoria dos Fractais, Bacharel em Matemática e Cientista da Computação, e trabalha com TI desde 1987, tendo trabalhado com desenvolvimento em Hardware, Firmware, C, C++, Pascal e Java. Atuou por mais de 20 anos com desenvolvimento em arquitetura orientada para Objetos. Especialista técnico do time de Hybrid Cloud IBM, com foco em BlockChain, PAK for Applications, PAK for Integration, Websphere, Modernização de aplicações, Microserviços, Kunernetes e OpenShift.
**LinkedIn:** https://www.linkedin.com/in/glaucoreis/
**Foto:** Usar a do LinkedIn

### Palestra 2:
**Titulo:**  Catalyst Blockchain Platform: facilitando a configuração e o gerenciamento de sua rede blockchain
**Palestrante:** Chaim Finizola
**MiniBio:** Head of Business Development Emerging Markets Chaim Finizola esteve envolvido no espaço blockchain des de 2016. Como Chefe de Desenvolvimento de Negócios em Mercados Emergentes na IntellectEU, uma fintech Belga especializada em novas tecnologias, ele tem sido responsável por reproduzir projectos de DLT Europeus em países como o Brasil. 
**LinkedIn:**  https://www.linkedin.com/in/chaimfinizola/ 
**Foto:** ![image](https://user-images.githubusercontent.com/31826218/88194943-cc2b7100-cc15-11ea-8696-1d4275fb9651.png)

**Comment by maxgaldinus** [comment]
Segue arte inicial.
[Hyperledger Social Card Design Meetup 2020 07 29.pptx](https://github.com/hyperledgerbrasil/meetup-br/files/4961316/Hyperledger.Social.Card.Design.Meetup.2020.07.29.pptx)

**Comment by rischioto** [comment]
Galdino 
Acho só que deviamos incluir os títulos das palestras e o horário né?

**Comment by maxgaldinus** [comment]
O que acha assim?
![image](https://user-images.githubusercontent.com/31826218/88208328-6ea02000-cc27-11ea-8702-1e01fe32fe08.png)

**Comment by rischioto** [comment]
Acho q já podemos soltar o Save the Date
