### ISSUE TITLE
Criar Evento CY20M03  no Meetup

### ISSUE THREAD

**Issue by rischioto** [hyperledgerbrasil/meetup-br#4]

**Comment by maxgaldinus** [comment]
O Capítulo Hyperledger Brasil tem o prazer em te convidar para o nosso próximo meetup virtual, que será sobre Plataformas de Blockchain com Hyperledger.

Teremos duas sessões sobre este tema. Na primeira o palestrante Glauco Reis da IBM irá apresentar a IBM Blockchain Platform 2.5. E na sequência o palestrante Chaim Finizola, da IntellectEU, irá apresentar a solução Catalyst Blockchain Platform. Ambas as soluções voltadas para redes permissionadas baseadas em Hyperledger Fabric.

Agenda:

* 18:00 Welcome - Anúncios e Novidades Chapter Brazil
* 18:10 IBM Blockchain Platform 2.5 - Glauco Reis
* 18:35 Catalyst Blockchain Platform - Chaim Finizola

Conheça nossos speakers:
Glauco Reis: https://www.linkedin.com/in/glaucoreis/
Chaim Finizola: https://www.linkedin.com/in/chaimfinizola/

Vamos com Tudo!

Dados para o Virtual Meeting:

**TBD**
